// Code generated by github.com/trevor-scheer/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type NewTodo struct {
	Text   string    `json:"text"`
	UserID string    `json:"userId"`
	UID    uuid.UUID `json:"uid"`
}

type Todo struct {
	ID   string    `json:"id"`
	Text string    `json:"text"`
	Done bool      `json:"done"`
	UID  uuid.UUID `json:"uid"`
}
